# This workflow will install Python dependencies and run with a variety of Python versions

name: Python package

on:
  push:
    branches: [ "bug_testing" ]
  pull_request:
    branches: [ "bug_testing" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9.12"]
        os: ["ubuntu-20.04", "windows-latest"]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy=1.23.*
        pip install -r requirements.txt
        pip install PyQt5
        pip install Cython
        pip install nose
    - name: Install package
      run: |
        python setup.py install
    - name: Test with nose
      run: |
        nosetests
