# This workflow will install Python dependencies and run with a variety of Python versions

name: Python package

on:
  - push
  - pull_request

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install -r requirements.txt
        pip install PyQt5
        pip install Cython
    - name: Install package
      run: |
        python setup.py build_ext --inplace
    - name: Run tests
      run: |
        python -m unittest -v
